services:
  - type: web
    name: vexor-ai
    env: node
    plan: free
    nodeVersion: "22" 
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: GOOGLE_PAGESPEED_API_KEY
        sync: false
      - key: GROQ_API_KEY    # <-- CHANGE THIS KEY
        sync: false
